<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<h1>Enregistrement des tris</h1>
<form class="m-5" action="Data/triPost" method="POST">
    <div class="mb-3">
    </div>
    <i class="bi bi-plus-square-fill ajout_ligne"></i><br>
    <input type="submit" value="Valider" id="submit" class="btn btn-primary">

</form>
<script src="public/javascript/select.js"></script>