<link rel="stylesheet" href="public/css/Map.css">
<link rel="stylesheet" href="public/css/style.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
<div class="container-fluid">
    <h1 class="text-center m-5">Présentation de l'association</h1>
    <p class="m-5">La Méditerranée : un trésor collectif.
        Espace unique pour les hommes comme pour la faune et la flore, la Méditerranée est un trésor collectif que nous avons la responsabilité de protéger. C’est un « point chaud » de biodiversité marine: 9% des espèces marines mondiales y sont recensées pour une superficie représentant 1% de la surface totale des océans de la planète !

        Depuis l’Antiquité, la mer Méditerranée constitue un patrimoine exceptionnel pour ses peuples riverains et l’ensemble de l’humanité. C’est sur ses rives que sont nés la démocratie, les monothéismes et nombre de civilisations aussi puissantes qu’influentes. Voie d’échanges à travers les siècles, son rôle socio-économique perdure pour les activités récréatives ou touristiques, le commerce maritime et la pêche professionnelle.

        En mer Méditerranée les déchets plastiques ne connaissent pas de frontières et se déplacent au gré des vents et des courants. Les initiatives de réduction des déchets initiées dans les pays européens de la rive nord du bassin Méditerranéen seront limitées voire inefficaces si elles ne sont pas développées et partagées avec les pays riverains de la rive Sud.

        « Interdire les sacs en plastique, ramasser les déchets sur les plages, trier ses poubelles ou acheter une gourde ne suffira pas à endiguer la pollution des mers et des océans ».
        95% des déchets plastiques qui arrivent en mer coulent et vouloir nettoyer les mers et les océans est une utopie. Pour réduire les déchets plastiques, il faut des politiques systémiques car les actions fragmentées et au coup par coup ne seront pas suffisantes.

        Cette mer semi-fermée est considérée comme la mer la plus polluée au monde avec quotidiennement l’arrivée de 730 tonnes de déchets provenant des bassins versants de l’ensemble des pays du littoral Méditerranéen. A l’origine des activités humaines terrestres et maritimes, cette hémorragie de déchets plastiques reste piégée et circule sur l’ensemble du bassin en s’accumulant également dans les fosses marines. En Méditerranée, ce sont 200.000 tonnes de déchets plastiques qui sont déversés chaque année dont 11000 tonnes proviennent de la France. Les micro-plastiques atteignent des niveaux records de concentration avec 1,25 million de fragments par km2, près de quatre fois le niveau de la zone la plus importante de concentration dans le Pacifique nord. Les sédiments marins sont affectés, atteignant par endroits des concentrations de fragments de plastique parmi les plus élevées au monde : 10 000 fragments par km2.</p>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="map-legend col-4">
            <h4>Légende de la carte</h4>
            <div class="legend black-icon">
                <img src="public/assets/icons/black.png" alt="black-icon" width="30">
                <span>Nb de microplastiques supérieur à 500</span>
            </div>
            <div class="legend marron-icon">
                <img src="public/assets/icons/maroon.png" alt="maroon-icon" width="30">
                <span>Nb de microplastiques entre 300 et 500</span>
            </div>
            <div class="legend red-icon">
                <img src="public/assets/icons/red.png" alt="red-icon" width="30">
                <span>Nb de microplastiques entre 100 et 300</span>
            </div>
            <div class="legend orange-icon">
                <img src="public/assets/icons/orange.png" alt="orange-icon" width="30">
                <span>Nb de microplastiques entre 50 et 100</span>
            </div>
            <div class="legend yellow-icon">
                <img src="public/assets/icons/yellow.png" alt="yellow-icon" width="30">
                <span>Nb de microplastiques entre 0 et 50</span>
            </div>

            <div class="box blue-box" style="background-color: blue;display:inline-block; width:30px; height:30px;"></div><span>Mer Méditerranée</span><br>
            <div class="box green-box" style="background-color: green;display:inline-block; width:30px; height:30px;"></div><span>Mer Tyrrhénienne</span>
            <br>
            <div class="box red-box" style="background-color: red;display:inline-block; width:30px; height:30px;"></div><span>Mer Ligurienne</span>
            <br>
            <div class="box orange-box" style="background-color: orange;display:inline-block; width:30px; height:30px;"></div><span>Bouches du Bonifacio</span>
            <br>
            <div class="box purple-box" style="background-color: purple;display:inline-block; width:30px; height:30px;"></div><span>Mer de Sardaigne</span>


        </div>

        <div id="map" class="rounded-1 m-15 col-7"></div>
    </div>
</div>

<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
<script src="public/javascript/map.js"></script>