<!DOCTYPE html>

<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php $pageTitle ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <base href="http://localhost/expedition-med/">
</head>

<body>
    <div class="container mb-5">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="https://www.expedition-med.org/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                <img class="img-fluid" src="public/assets/img/logo.svg" alt="Logo de l'association Expedition Med">
            </a>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="users/index" class="nav-link px-2 link-secondary">Accueil</a></li>
                <?php if (isset($_SESSION['id'])) { ?>
                    <li><a href="data/sampling" class="nav-link px-2 link-dark">Prélèvements</a></li>
                    <li><a href="data/tri" class="nav-link px-2 link-dark">Tri</a></li>
                    <li><a href="admin/index" class="nav-link px-2 link-dark">Administration</a></li>
                    <li><a href="admin/importExcel" class="nav-link px-2 link-dark">Import fichier Excel</a></li>


                <?php } ?>
            </ul>

            <div class="col-md-3 text-end">
                <?php if (isset($_SESSION['id'])) { ?>
                    <a href="users/register" type="button" class="btn btn-primary">Ajouter un utilisateur</a>
                    <a href="users/logout" type="button" class="btn btn-primary">Logout</a>

                <?php  } else { ?>
                    <a href="users/login" type="button" class="btn btn-outline-primary me-2">Login</a>
                <?php } ?>
            </div>
        </header>
    </div>



    <main>
        <?php require_once $page; ?>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>

</html>