<form class="m-5" method="POST" action="Users/registerPost">
    <div class="mb-3">
        <label for="Email" class="form-label">Adresse Email</label>
        <input type="email" class="form-control" id="Email" name="email" aria-describedby="input your Email Adress">
    </div>
    <div class="mb-3">
        <label for="Password" class="form-label">Mot de Passe</label>
        <input type="password" class="form-control" id="Password" name="password">
    </div>
    <div class="mb-3">
        <label for="Password2" class="form-label">Retapez votre mot de Passe</label>
        <input type="password" class="form-control" id="Password2" name="password2">
    </div>
    <div class="text-center"><button type="submit" name="submit" class="btn btn-primary">S'inscrire'</button></div>
    <?php
    if (isset($erreur)) {
        echo "<p style='color:red'>$erreur</p>";
    }
    ?>

</form>