<h2>Tri pour le Sample <?= $tri[0]["Sample"] ?></h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Taille</th>
            <th scope="col">Type</th>
            <th scope="col">Couleur</th>
            <th scope="col">Nombre</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($tri as $tri) : ?>
            <tr>
                <td><?= $tri["size"] ?></td>
                <td><?= $tri["type"] ?></td>
                <td><?= $tri["color"] ?></td>
                <td><?= $tri["Number"] ?></td>
                <td><a href="admin/editByTri/<?= $tri["id"] ?>">Modifier</a></td>
                <td><a href="admin/deleteByTri/<?= $tri["id"] ?>" onclick="return confirm('Confirmer la suppression de ce tri');">Supprimer</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>