<h1 class="text-center">Prélèvement <?= $result["Sample"] ?></h1>

<ul class="list-group w-50 mx-auto">
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Campagne
        <span class="badge bg-primary rounded-pill"><?= $result["Campagne"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Mer
        <span class="badge bg-primary rounded-pill"><?= $result["Sea"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Manta
        <span class="badge bg-primary rounded-pill"><?= $result["Manta"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Date
        <span class="badge bg-primary rounded-pill"><?= $result["Date"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Trafic
        <span class="badge bg-primary rounded-pill"><?= $result["Trafic"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Cote la plus proche
        <span class="badge bg-primary rounded-pill"><?= $result["cote_la_plus_proche"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Courant
        <span class="badge bg-primary rounded-pill"><?= $result["courant"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Heure de Départ
        <span class="badge bg-primary rounded-pill"><?= $result["Start_Time_UTC"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Heure d'Arrivée
        <span class="badge bg-primary rounded-pill"><?= $result["End_Time_UTC"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Latitude de Départ
        <span class="badge bg-primary rounded-pill"><?= $result["Start_Latitude"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Longitude de Départ
        <span class="badge bg-primary rounded-pill"><?= $result["Start_Longitude"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Latitude moyenne
        <span class="badge bg-primary rounded-pill"><?= $result["Mid_Latitude"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Longitude moyenne
        <span class="badge bg-primary rounded-pill"><?= $result["Mid_Longitude"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Latitude de Fin
        <span class="badge bg-primary rounded-pill"><?= $result["End_Latitude"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Longitude de Fin
        <span class="badge bg-primary rounded-pill"><?= $result["End_Longitude"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Vitesse du bâteau
        <span class="badge bg-primary rounded-pill"><?= $result["Boat_Speed_kt"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Force du vent
        <span class="badge bg-primary rounded-pill"><?= $result["Wind_Force_B"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Vitesse du vent
        <span class="badge bg-primary rounded-pill"><?= $result["Wind_Speed_kt"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Direction du vent
        <span class="badge bg-primary rounded-pill"><?= $result["Wind_Direction_deg"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Etat de la mer
        <span class="badge bg-primary rounded-pill"><?= $result["Sea_State_B"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Température de l'eau
        <span class="badge bg-primary rounded-pill"><?= $result["Temperature_C"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        PH
        <span class="badge bg-primary rounded-pill"><?= $result["pH"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Oxygene Dissous
        <span class="badge bg-primary rounded-pill"><?= $result["Oxygene_Dissous_mg_L"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Salinité
        <span class="badge bg-primary rounded-pill"><?= $result["Salinite_SAL_PSU"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Début débimètre
        <span class="badge bg-primary rounded-pill"><?= $result["Start_Flowmeter"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Fin débimètre
        <span class="badge bg-primary rounded-pill"><?= $result["End_Flowmeter"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Volume filtrée
        <span class="badge bg-primary rounded-pill"><?= $result["Volume_Filtered_m3"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Distance
        <span class="badge bg-primary rounded-pill"><?= $result["Filtered_Distance"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Volume
        <span class="badge bg-primary rounded-pill"><?= $result["Volume_m3"] ?></span>
    </li>

    <li class="list-group-item d-flex justify-content-between align-items-center">
        Km2
        <span class="badge bg-primary rounded-pill"><?= $result["km2"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Nombre de particules
        <span class="badge bg-primary rounded-pill"><?= $result["Nombre_Particules_gt_1_mm"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Concentration surfacique
        <span class="badge bg-primary rounded-pill"><?= $result["Concentration_nb_km2"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Concentration volumique
        <span class="badge bg-primary rounded-pill"><?= $result["Concentration_nb_m3"] ?></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Commentaires
        <span class="badge bg-primary rounded-pill"><?= $result["Commentaires"] ?></span>
    </li>
</ul>